### ISSUE TITLE
Adding repos

### ISSUE THREAD

**Issue by soham117** [manisha069/HacktoberFest21#1]
can I contribute to beginner-friendly repo list in readme.md?

**Comment by manisha069** [comment]
Yes, anyone can contribute to those...I'm still waiting for a lot of maintainers to update their labels on repos and curating the list to provide good repos. 
So do hang on for a while till the list is uploaded on the Readme 😅😅

**Comment by soham117** [comment]
Ok I will curate some repos and contribute tomorrow if u don't mind. I have curated a couple of repos actually

**Comment by manisha069** [comment]
That would be extremely helpful!

**Comment by manisha069** [comment]
I am still working on most stuff, most probably this would have a basic list of algorithms and data - structure related directories for users to contribute to since these are the basic thigs first timers specially find simple to begin with hence the contributing guidelines would be on the lines of no spammy PR and stuff like that and nothing serious or strict.

Do let me know your thoughts!

**Comment by manisha069** [comment]
Great!

**Comment by soham117** [comment]
I have submitted my PR pls let me know any changes
